import Head from "next/head";
import Link from "next/link";
import { useState } from "react";
import { Button } from "~/components/ui/button";
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from "~/components/ui/card";
import { Input } from "~/components/ui/input";
import { api } from "~/utils/api";
type choice = {
  choicesText: string;
};
export default function Home() {
  const [state, setState] = useState("");
  const [choices, setChoices] = useState<choice[]>([]);
  const [choicesText, setChoicesText] = useState("");
  const allPolls = api.pollRouter.getAllPollsByCreatedAt.useQuery();

  // In component:
  const utils = api.useContext();
  console.log(choices);
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="dark flex min-h-screen flex-col items-center justify-center  ">
        <div className="container   grid grid-cols-3 justify-center gap-12 px-4 py-16 ">
          {allPolls.data?.map((item) => (
            <>
              <Card className="hover:border-slate-600">
                <CardHeader>
                  <CardTitle>Umfage</CardTitle>
                  <CardDescription>
                    <div>{item.question}</div>
                  </CardDescription>
                </CardHeader>
                <CardContent>
                  <div>{item.link}</div>
                  <div>{item.createdAt.toString()}</div>
                  <div>
                    {item.choices.map((choice) => (
                      <div>{choice.choiceText}</div>
                    ))}
                  </div>
                </CardContent>
              </Card>
            </>
          ))}
        </div>
      </main>
    </>
  );
}
